[project]
name = "terraform-ansible-k3s"
version = "0.1.0"
requires-python = ">=3.13.11"
dependencies = [
    "ansible>=13.1.0",
    "ansible-builder>=3.1.1",
    "ansible-lint>=25.12.1",
]
[tool.uv]
required-version = ">=0.9.10"
